services:
    _defaults:
        autowire: false
        autoconfigure: false

    tiriel.firestore_odm.dto_manager:
        class: Tiriel\FirestoreOdmBundle\FirestoreDtoManager
        abstract: true
        tags: ['firestore_odm.manager']

    tiriel.firestore_odm.cacheable_manager:
        class: Tiriel\FirestoreOdmBundle\Manager\CacheableFirestoreDtoManager
        decorates: 'tiriel.firestore_odm.dto_manager'

    tiriel.firestore_odm.dto_value_resolver:
        class: Tiriel\FirestoreOdmBundle\ValueResolver\FirestoreDtoValueResolver
        tags:
            - 'controller.argument_value_resolver':
                name: 'firestore_dto'

