services:
    _defaults:
        autowire: false
        autoconfigure: false

    tiriel.firestore_odm.dto_id_normalizer:
        class: Tiriel\FirestoreOdmBundle\Serializer\Normalizer\DtoIdNormalizer
        arguments:
            $normalizer: '@serializer.normalizer.object'

    tiriel.firestore_odm.dto_manager:
        class: Tiriel\FirestoreOdmBundle\Manager\FirestoreDtoManager
        abstract: true

    tiriel.firestore_odm.cacheable_manager:
        class: Tiriel\FirestoreOdmBundle\Manager\CacheableFirestoreDtoManager
        decorates: 'tiriel.firestore_odm.dto_manager'

    tiriel.firestore_odm.dto_value_resolver:
        class: Tiriel\FirestoreOdmBundle\ValueResolver\FirestoreDtoValueResolver
        arguments:
            $locator: !tagged_locator { tag: firestore_odm.manager, index_by: dto }
        tags:
            - 'controller.argument_value_resolver':
                  name: 'firestore_dto'

